version: "3.8"

services:
  nextjs-app:
    container_name: nextjs-app
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
